config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :messages, only: [:new, :create]

  resources :crossfit_name_generator, only: [:new, :create]

  resources :words

  resources :financial_entries

  resources :blog_posts
  get '/sitemap.xml', to: 'pages#sitemap', :format => "xml", :as => :sitemap

  get 'blog/new', to: 'blog_posts#new'
  post 'blog/login', to: 'blog_posts#verify'
  post 'blog/logout', to: 'blog_posts#logout', as: "logout"

  get '/blog' => 'blog_posts#index', as: "blog"
  get '/blog/:slug', to: 'blog_posts#show'

  get '/twilio_inbox' => 'twilio#inbox'
  get '/twilio' => 'twilio#index'

  get '/twilio_reminders' => 'twilio_reminders#index'

  post '/twilio_reminders' => 'twilio_reminders#create'

  get '/send_reminder/:id' => 'twilio_reminders#send_reminder', as: "send_reminder"

  get '/delete_reminder/:id' => 'twilio_reminders#delete_reminder', as: "delete_reminder"

  get '/cookie_voting', to: "cookie_voting#index"

  post '/business-hook' => 'fitnesstexter#webhook'

  resources :contact_form, only: [:index, :new, :create]

end

app/views/shared/_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54527037-1', 'auto');
  ga('send', 'pageview');

app/views/shared/_crossfit_names.html.haml
- unless @business_names == nil
  - @business_names.each do |name|
    .small-12.large-4.columns.centered
      %h4{class: 'button radius info', style: 'width: 300px;'}
        CrossFit
        =name.capitalize

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .alert.alert-danger
    - obj.errors.full_messages.each do |e|
      = e

app/views/shared/_flash_messages.html.haml
.row
  .small-12.columns
    .div.centered{style: "margin-top: 5px;"}
      - flash.each do |name, msg|
        %div(data-alert=true class="alert-box #{name} radius")
          %a.close(href="#")
            &times;
          = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/shared/_footer.html.haml
= javascript_include_tag "application"

app/views/shared/_header.html.haml
.contain-to-grid
  %nav.top-bar{role: 'navigation', data: {topbar:''}}
    %ul.title-area
      %li.name
        %h1
          =link_to "Patrick Jones: Junior Ruby on Rails Developer", root_path
      %li.toggle-topbar.menu-icon
        %span Menu
    %section.top-bar-section
      %ul.right
        /%li.divider
        /%li=link_to "Suggest an API Mashup"
        %li.divider
        %li=link_to "Blog", "/blog"
        %li.divider
        %li.has-dropdown.not-click
          = link_to "Patrick's Projects & External API Integrations"
          %ul.dropdown
            %li= link_to "TryPaper.com PDF Mailer App", '/trypaper-api-ruby-web-application'
            %li= link_to "GitHub Coding Leaderboard", '/github-coding-leaderboard'
            %li= link_to "Twilio SMS Reminders", twilio_reminders_path
            %li= link_to "CrossFit Name Generator", new_crossfit_name_generator_path
            %li= link_to "Mandrill Contact Form", contact_form_index_path
            %li= link_to "Twilio to Screen", twilio_path