config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :messages, only: [:new, :create]

  resources :crossfit_name_generator, only: [:new, :create]

  resources :words

  resources :financial_entries

  resources :blog_posts
  get '/sitemap.xml', to: 'pages#sitemap', :format => "xml", :as => :sitemap

  get 'blog/new', to: 'blog_posts#new'
  post 'blog/login', to: 'blog_posts#verify'
  post 'blog/logout', to: 'blog_posts#logout', as: "logout"

  get '/blog' => 'blog_posts#index', as: "blog"
  get '/blog/:slug', to: 'blog_posts#show'

  get '/twilio_inbox' => 'twilio#inbox'
  get '/twilio' => 'twilio#index'

  get '/twilio_reminders' => 'twilio_reminders#index'

  post '/twilio_reminders' => 'twilio_reminders#create'

  get '/send_reminder/:id' => 'twilio_reminders#send_reminder', as: "send_reminder"

  get '/delete_reminder/:id' => 'twilio_reminders#delete_reminder', as: "delete_reminder"

  get '/cookie_voting', to: "cookie_voting#index"

  post '/business-hook' => 'fitnesstexter#webhook'

  resources :contact_form, only: [:index, :new, :create]

end

app/models/twilio_reminder.rb
class TwilioReminder < ActiveRecord::Base

  validates :client, presence: true
  validates :event, presence: true

  validates :phone_number, presence: true
  validates :phone_number, length: { is: 12, message: "must be styled like: 555-555-5555" }
end

app/controllers/twilio_reminders_controller.rb
class TwilioRemindersController < ApplicationController
require 'twilio-ruby'

  def index
    #@reminder = TwilioReminder.new
    @reminders = TwilioReminder.all
    @twilio_reminder = TwilioReminder.new
  end

  def create
    #binding.pry
    @reminders = TwilioReminder.all
    @twilio_reminder = TwilioReminder.new(message_params)

    #binding.pry

    if @twilio_reminder.save
      redirect_to twilio_reminders_path
    else
      #flash.now[:error] = "Something went wrong with your inputs."
      #binding.pry
      render :index
    end

  end

  def send_reminder
    #binding.pry

    reminder = TwilioReminder.find(params[:id])

    user_phone_number = reminder.phone_number.remove("-").prepend("+1")

    @client = Twilio::REST::Client.new ENV["TWILIO_SID"], ENV["TWILIO_TOKEN"]

    message = @client.account.messages.create(
      :body => "Patrick's Twilio App: Hi #{reminder.client}. Your #{reminder.event} is ready for pickup. Do not reply to this message.",
      :to => "#{user_phone_number}",
      :from => "+17208973141"
      )

    message.to

    patrick_message = @client.account.messages.create(
      :body => "Someone just used your SMS API. Congrat-u-fucking-lations!",
      :to => "+16124379264",
      :from => "+17208973141"
      )

    patrick_message.to

    reminder.message_sent = true

    reminder.save

    #binding.pry

    redirect_to twilio_reminders_path

  end

  def delete_reminder

    #binding.pry

    reminder = TwilioReminder.find(params[:id])

    reminder.delete

    redirect_to twilio_reminders_path

  end


  private

  def message_params
    params.require(:twilio_reminder).permit(:client, :event, :phone_number)
  end


end

app/views/twilio_reminders/index.html.haml
- @title = "Building an SMS Reminders Application using Twilio API"
.row
  .small-12.columns.centered
    %h2 Twilio Text Message Reminders
.row
  .small-12.columns
    %p This is an experimental application that businesses would use to send a "Your Item is Ready for Pickup" text message to clients.
    %p I was walking home from the grocery store and this idea came to me. 12 hours later, it's a real thing!
    %ol{:type => "1"}
      %li Input your name, hypothetical item that needs to be picked up, and your phone number
      %li Task item will populate below the input form
      %li Click "Ready for Pickup"
      %li Twilio API sends a customized "Your Item is Ready for Pickup" text message to your phone
      %li "Ready for Pickup" button is deactivated to prevent abuse
      %li Click "Remove Item" to remove your task from the list
    %b Please only use your PERSONAL phone number. Please don't put my career in jeopardy by abusing this. Thanks!
    %hr
/ .row
/   .small-12.columns
/     - if @twilio_reminder == nil
/     - else
/       = render 'shared/errors', obj: @twilio_reminder
/     = form_for @twilio_reminder do |f|
/       %fieldset
/         %legend Set Up Text Message Reminder
/         .row
/           .small-12.large-4.columns
/             = f.label :client, "Client Name"
/             = f.text_field :client, class: 'radius', placeholder:"Customer Name"
/           .small-12.large-4.columns
/             = f.label :event, "Item to be Picked Up"
/             = f.text_field :event, class: 'radius', placeholder:"Item to Be Picked Up [Sandwich, dry cleaning, etc]"
/           .small-12.large-4.columns
/             = f.label :phone_number, "Phone Number"
/             = f.text_field :phone_number, class: 'radius', placeholder:"Phone Number [Written as 555-555-5555]"
/         .row
/           .small-12.columns.centered
/             = f.submit "Create Pickup Reminder", class:'button alert radius'
/       %br
/ .row
/   .small-12.columns
/     - if @reminders.count != 0
/       %h4 Current Events Waiting for Reminders
/ .row
/   - @reminders.each do |r|
/     .small-12.large-6.columns
/       .panel.radius{style: "height: 150px;"}
/         %p
/           %b Client Name:
/           = r.client
/         %p
/           %b Item to be Picked Up:
/           = r.event
/         - if r.message_sent == true
/           .label Reminder Has Been Sent Successfully
/         - else
/           = link_to "Click to Send Pickup Reminder", send_reminder_path(r), { :style => "margin-bottom: 5px;", :class => 'success label'}
/         = link_to "Remove Item", delete_reminder_path(r), class:  'alert label'