config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :messages, only: [:new, :create]

  resources :crossfit_name_generator, only: [:new, :create]

  resources :words

  resources :financial_entries

  resources :blog_posts
  get '/sitemap.xml', to: 'pages#sitemap', :format => "xml", :as => :sitemap

  get 'blog/new', to: 'blog_posts#new'
  post 'blog/login', to: 'blog_posts#verify'
  post 'blog/logout', to: 'blog_posts#logout', as: "logout"

  get '/blog' => 'blog_posts#index', as: "blog"
  get '/blog/:slug', to: 'blog_posts#show'

  get '/twilio_inbox' => 'twilio#inbox'
  get '/twilio' => 'twilio#index'

  get '/twilio_reminders' => 'twilio_reminders#index'

  post '/twilio_reminders' => 'twilio_reminders#create'

  get '/send_reminder/:id' => 'twilio_reminders#send_reminder', as: "send_reminder"

  get '/delete_reminder/:id' => 'twilio_reminders#delete_reminder', as: "delete_reminder"

  get '/cookie_voting', to: "cookie_voting#index"

  post '/business-hook' => 'fitnesstexter#webhook'

  resources :contact_form, only: [:index, :new, :create]

end

app/models/financial_entry.rb
class FinancialEntry < ActiveRecord::Base
  validates :name, presence: true
  validates :amount, presence: true
end

app/controllers/financial_entries_controller.rb
class FinancialEntriesController < ApplicationController

  def index
    @financial_entries = FinancialEntry.all.order('updated_at DESC')
  end

  def create
    begin
      @financial_entry = FinancialEntry.new(financial_entry_param)

      if @financial_entry.save 
        @financial_entries = FinancialEntry.all.order('updated_at DESC')
      else
        @error_message = "Error: You cannot save that value."
      end
    rescue => e 
      @error_message = "#{e.class}"
    end
  end

  def edit 
    @financial_entry = FinancialEntry.where(id: params[:id]).first

    unless @financial_entry
      redirect_back(fallback_location: root_path) and return
    end
  end

  def update 
    @financial_entry = FinancialEntry.where(id: params[:id]).first

    if @financial_entry.update(financial_entry_param)
      flash[:success] = "Updated successfully!"
    else
      flash[:error] = "Error: Could not update."
    end
    redirect_to financial_entries_path
  end


  def destroy
    @financial_entry = FinancialEntry.where(id: params[:id]).first

    if @financial_entry
      @financial_entry.destroy
    else
      @error_message = "Error: You cannot delete that value."
    end

  end

  private

  def financial_entry_param
    params.require(:financial_entry).permit(:name, :amount)
  end

end

app/views/financial_entries/_list_view.html.haml
- financial_entries.each do |entry|
  .panel{id: "financial_entry_holder_#{entry.id}"}
    %p
      = button_to "Delete", financial_entry_path(entry.id), method: :delete, style: "float: right;", remote: true, data: {disable_with: "Deleting..."}
      = link_to "Edit", edit_financial_entry_path(entry.id), style: "float: right; margin-right: 10px;"
      <b>Name:</b> #{entry.name} <b>Amount:</b> #{number_to_currency(entry.amount, unit: "$")}

app/views/financial_entries/create.js.haml
- if @error_message
  alert("#{sanitize @error_message}");
- else
  $("#financial_entry_name").val('');
  $("#financial_entry_amount").val('');
  $('#financial_entries_holder').html("#{escape_javascript(render 'financial_entries/list_view', financial_entries: @financial_entries)}");

app/views/financial_entries/destroy.js.haml
- if @error_message
  alert("#{sanitize @error_message}");
- else
  $("#financial_entry_holder_#{@financial_entry.id}").hide();

app/views/financial_entries/edit.html.haml
.row
  .small-12.columns
    %h3.centered
      Edit Financial Entry Page
    %hr
.row
  .small-12.columns
    = form_for @financial_entry  do |f|
      %fieldset
        %legend Create Financial Entry
        .row
          .small-12.large-6.columns
            = f.label :name, "Name"
            = f.text_field :name, class: "radius"
          .small-12.large-6.columns
            = f.label :amount, "Amount"
            = f.text_field :amount, class: "radius"
          .small-12.columns.centered
            = f.submit 'Update', class: "button radius alert right", data:{disable_with: "Processing..."}

app/views/financial_entries/index.html.haml
.row
  .small-12.columns
    %h3.centered
      Financial Entries Page
    %hr
.row
  .small-12.columns
    = form_tag financial_entries_path, action: "create", remote: "true" do
      %fieldset
        %legend Create Financial Entry
        .row
          .small-12.large-6.columns
            = text_field_tag "financial_entry[name]", nil, class: "radius"
          .small-12.large-6.columns
            = text_field_tag "financial_entry[amount]", nil, class: "radius"
          .small-12.columns.centered
            = submit_tag 'Save', class: "button radius alert right", data:{disable_with: "Processing..."}
.row
  .small-12.columns
    #financial_entries_holder
      = render 'financial_entries/list_view', financial_entries: @financial_entries