config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :messages, only: [:new, :create]

  resources :crossfit_name_generator, only: [:new, :create]

  resources :words

  resources :financial_entries

  resources :blog_posts
  get '/sitemap.xml', to: 'pages#sitemap', :format => "xml", :as => :sitemap

  get 'blog/new', to: 'blog_posts#new'
  post 'blog/login', to: 'blog_posts#verify'
  post 'blog/logout', to: 'blog_posts#logout', as: "logout"

  get '/blog' => 'blog_posts#index', as: "blog"
  get '/blog/:slug', to: 'blog_posts#show'

  get '/twilio_inbox' => 'twilio#inbox'
  get '/twilio' => 'twilio#index'

  get '/twilio_reminders' => 'twilio_reminders#index'

  post '/twilio_reminders' => 'twilio_reminders#create'

  get '/send_reminder/:id' => 'twilio_reminders#send_reminder', as: "send_reminder"

  get '/delete_reminder/:id' => 'twilio_reminders#delete_reminder', as: "delete_reminder"

  get '/cookie_voting', to: "cookie_voting#index"

  post '/business-hook' => 'fitnesstexter#webhook'

  resources :contact_form, only: [:index, :new, :create]

end

app/controllers/crossfit_name_generator_controller.rb
class CrossfitNameGeneratorController < ApplicationController

  def new
    @counter = Counter.where(name:"CrossFit").first
  end

  def create
    @counter = Counter.where(name:"CrossFit").first

      respond_to do |format|

        format.js do

          if params[:query].empty? || ((params[:query] =~ /\s/).nil? == false)

          else

            require 'net/http'

            uri = URI("http://words.bighugelabs.com/api/2/#{ENV['BIG_THES_KEY']}" + "/" + "#{params[:query]}" + "/json")

            res = Net::HTTP.get_response(uri)

            if res.code != "200"
              @message = "That word doesn't exist in our dictionary."
            else

              hash = JSON.parse(res.body)

              @business_names = []

              hash.keys.each do |x|
                if x == "adjective"
                  hash.fetch("adjective")["sim"].each{ |x| @business_names << x }
                elsif x == "noun"
                  hash.fetch("noun")["syn"].each{ |x| @business_names << x }
                end
              end
              @counter.count += 1
              @counter.save
            end

          end #end of if statement

        end #end of format.js

    end #end of respond_to

  end # end of create action

  def show
  end

end

app/views/crossfit_name_generator/create.js.erb
<% if @message %>
  alert("That word doesn't exist in the dictionary. Try again.")
<% else %>
  $("#crossfit-counter").html("<%= @counter.count %> times")
  $("#crossfit-names").html("<%= escape_javascript(render(:partial => 'shared/crossfit_names')) %>")
<% end %>

app/views/crossfit_name_generator/new.html.haml
- @title = "CrossFit Box & Gym Business Name Idea Generator"
- @metadescription = "The FitnessTexter CrossFit box & gym business name generator gives you hundreds of possible business names for your gym."
.row
  .small-12.columns.centered
    %h2 CrossFit Box & Gym Business Name Generator
  %hr
.row
  .small-12.large-6.columns
    %p
      Howdy! For a fun side project, I built the CrossFit & gym name generator, which is powered by the #{ link_to 'Big Thesaurus API', 'http://words.bighugelabs.com/', :target => 'blank'}.
    %p
      Input a "starting word" for your CrossFit box business name. Use words like
      %b angry, fierce, strong,
      etc. Click "Generate Names" and a list of possible CrossFit box affiliate names will be generated.
    %p
      If you already own a gym and are looking for a way to get more gym members, please check out my company #{ link_to 'FitnessTexter', 'http://boostfitnessmarketing.com/fitnesstexter', :target => 'blank'}. We provide text message marketing service for gyms and have worked with over 500 fitness businesses.
    %p
      %a{:href => "http://boostfitnessmarketing.com/fitnesstexter"}
        %img{:style => "width: 75%", :src => "http://boostfitnessmarketing.com/wp-content/uploads/boost-fitness-marketing-fitnesstexter-logo.png"}
  .small-12.large-6.columns
    <iframe style="border:2px solid black;" width="600" height="338" src="https://www.youtube.com/embed/8LBacdLm5xc" frameborder="0" allowfullscreen></iframe>
.row
  .small-12.columns
    %p{style: 'font-size: 10px;'}
      CrossFit is a registered trademark of CrossFit, Inc. All products mentioned are registered trademarks or trademarks of their respective companies. Their use does not imply any affiliation with, endorsement by, or certification by the respective trademark holder.
      %a{href: 'http://www.crossfit.com/how-to-affiliate', target: '_blank', title: 'Become CrossFit Affiliate'}Click here to become a CrossFit affiliate.
  %hr
.row
  .small-12.columns
    = form_tag crossfit_name_generator_index_path, action: "create", remote: "true" do
      %fieldset
        %legend CrossFit Box & Gym Name Business Name Generator
        .row
          .small-12.column.centered
            %p{style: 'font-size: 15px; font-weight: bold;'}
              Please "Like" my business page below, that's all I ask. More "likes" keep the name generator free! :)
            %p{style: 'font-size: 13px; font-weight: bold;'}
              Thanks -Patrick
            %p
              %a{ :href => "/crossfit_name_generator/new" } CrossFit Box Business Name Generator
            %p{:style => "margin-left: 50px;"}
              <iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FFitnessTexter&amp;width&amp;layout=standard&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=80&amp;appId=1386285168291466" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:80px;" allowTransparency="true"></iframe>
          %hr
          .small-6.small-centered.columns
            = text_field_tag :query, nil, class: "radius", placeholder: "Enter adjective like fierce, wild, strong, brave, etc"
          .small-12.columns.centered
            = submit_tag('Generate Names', class: "button radius alert")
            %br
            %p
              Used by future CrossFit owners
              %span#crossfit-counter
                = "#{@counter.count} times"
              and counting!
          %hr
          .panel-body#crossfit-names{ :style => "text-align: center;"}
  %hr
.row
  .small-12.columns
    %h4 How It Works
    %p
      1. Input word is sent to Big Thesaurus API via a Rails AJAX request using the 'net/http' library
      %br
      2. Big Thesaurus looks up word, and if it exists, it sends back a JSON file with synonyms, antonyms, etc
      %br
      3. JSON file is parsed for just the synonyms hash
      %br
      4. Hash is set as an instance variable
      %br
      5. Iterate over the instance variable of synonyms, prepending the word "CrossFit" to each.
    %hr